FROM rocker/tidyverse:4.5.1

# RUN \
#   echo 'options(repos=c(CRAN="https://packagemanager.posit.co/cran/__linux__/bookworm/latest"))' >> ~/.Rprofile && \
#   Rscript --vanilla -e 'getOption("repos")'

# Adding R packages
RUN install2.r netdiffuseR

RUN install2.r languageserver httpgd

RUN quarto install tinytex

CMD ["bash"]
